// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sigyknqancwvmyxbhwho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZ3lrbnFhbmN3dm15eGJod2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODg3NDksImV4cCI6MjA2NDY2NDc0OX0.K1LGcliYVKhsAtH0GZjzbPjagSbWOUmiVZC5o6fUZcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);